export { useProximityHover } from './useProximityHover'
export type { ProximityHoverOptions } from './useProximityHover'
export { HIGHLIGHT_ATTR, ITEM_ATTR, KEYBOARD_ATTR } from '@guillemservera/details-core/proximity-hover'
export type { HighlightAxis, HighlightSource } from '@guillemservera/details-core/proximity-hover'
export type { HighlightState } from '../shared/highlight'
