export { createArrowNavigation } from './arrow-navigation/createArrowNavigation'
export type { ArrowNavigationOptions } from './arrow-navigation/createArrowNavigation'
export { createHighlightIndicator } from './highlight-indicator/createHighlightIndicator'
export type { HighlightIndicatorOptions } from './highlight-indicator/createHighlightIndicator'
export { createProximityHover } from './proximity-hover/createProximityHover'
export type { ProximityHoverOptions } from './proximity-hover/createProximityHover'
export { createRollingText } from './rolling-text/createRollingText'
export type { RollingTextOptions } from './rolling-text/createRollingText'
export { createMorphText } from './morph-text/createMorphText'
export type { MorphTextOptions } from './morph-text/createMorphText'
export { createRouletteText } from './roulette-text/createRouletteText'
export type { RouletteTextOptions } from './roulette-text/createRouletteText'
export { createHighlightStore, HIGHLIGHT_ATTR, ITEM_ATTR, KEYBOARD_ATTR } from './shared/highlight'
export type { HighlightAxis, HighlightBehavior, HighlightSource, HighlightStore } from './shared/highlight'
export type { MaybeGetter } from './shared/options'
export type { TextMotion, TextMotionOptions } from './shared/textMotion'
export * from './platform'
export * from './input-capabilities'
export * from './shortcuts'
