export { useArrowNavigation, useHighlightStore } from './useArrowNavigation'
export type { ArrowNavigationOptions } from './useArrowNavigation'
export { HIGHLIGHT_ATTR, ITEM_ATTR, KEYBOARD_ATTR } from '@guillemservera/details-core/arrow-navigation'
export type { HighlightAxis, HighlightSource, HighlightStore } from '@guillemservera/details-core/arrow-navigation'
export type { HighlightState, HighlightStoreState } from '../shared/highlight'
